[profile.default]
src = 'contracts'
out = 'out'
libs = ['../lib']
script = 'script'
test = 'test'
cache_path = 'cache_forge'
fs_permissions = [{ access = "read", path = "./" }]

solc = "0.8.30"
sizes = true
optimizer = true
viaIR = true
optimizer_runs = 1

remappings = [
    "forge-std/=../lib/crane/lib/forge-std/src/",
    "@crane/=../lib/crane/",
    "@solady/=../lib/crane/lib/solady/src/",
    "@openzeppelin/=../lib/crane/lib/openzeppelin-contracts/",
]

ignored_error_codes = [2394, 3860, 5574, 2072]

[rpc_endpoints]
local = "http://127.0.0.1:8545"
